accounts/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('signup/',views.signup_view,name='signup'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
import mydiary.views
import accounts.views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mydiary.views.home,name="home"),
    path('new/', mydiary.views.new,name="new"),
    path('aboutus/', mydiary.views.aboutus,name="aboutus"),
    path('forlion/', mydiary.views.forlion,name="forlion"),
    path('recruit/',mydiary.views.recruit,name='recruit'),
    path('QA/',mydiary.views.QA,name='QA'),
    path('detail/<int:index>',mydiary.views.detail, name="detail"),
    path('edit/<int:index>',mydiary.views.edit, name="edit"),
    path('detail/<int:pk>/delete',mydiary.views.delete, name="delete"),
    path('detail/<int:index>/comment/<int:comment_pk>/delete/',mydiary.views.delete_comment, name="delete_comment"),
    path('tagadd/<int:pk>', mydiary.views.tag_add, name="tag_add"),
    path('tag',mydiary.views.tag_home, name="tag_home"),
    path('hashtag/<int:pk>', mydiary.views.tag_detail,name="tag_detail"),
    path('detail/<int:pk>/tag/<int:tag_pk>/delete', mydiary.views.tag_delete,name="tag_delete"),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    nickname=models.CharField(max_length=100)
    major=models.CharField(max_length=50)
    MBTI=models.CharField(max_length=50)

mydiary/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
# Create your models here.

class Content(models.Model):
    title=models.CharField(max_length=200)
    pub_date=models.DateTimeField(default=timezone.now)
    body=models.TextField(default='')
    tags=models.ManyToManyField('Tag', blank=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    objects= models.Manager()
    post= models.ForeignKey('Content', on_delete=models.CASCADE)
    text=models.TextField(default='')
    created_date=models.DateTimeField(default=timezone.now)

class Tag(models.Model):
    name=models.CharField(max_length=10)

    def __str__(self):
        return self.name

class Image(models.Model):
    post=models.ForeignKey(Content,on_delete=models.CASCADE)
    file=models.ImageField(upload_to='images/', blank=True, null=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class SignupForm(UserCreationForm):
    class Meta:
        model=CustomUser
        fields=['username','password1','password2','nickname','major','MBTI']

mydiary/forms.py
from django import forms
from django.db.models import fields
from .models import Comment, Content, Tag

class ContentForm(forms.ModelForm):
    class Meta:
        model = Content
        fields=['title','body']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields=["text"]

class TagForm(forms.ModelForm):
    class Meta:
        model =Tag
        fields=['name']

accounts/views.py
from django.contrib import auth
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from .forms import SignupForm
# Create your views here.

def signup_view(request):
    if request.method=="POST":
        form=SignupForm(request.POST)
        if form.is_valid():
           user=form.save()
           login(request,user)
           return redirect('home')
    else:
        form=SignupForm()
    return render(request, 'signup.html', {'form':form})

def login_view(request):
    if request.method=="POST":
        form=AuthenticationForm(request.POST)
        if form.is_valid():
           username=form.cleaned_data.get("username")
           password=form.cleaned_data.get("password")
           user=authenticate(request=request, username=username, password=password)
           if user is not None:
               login(request, user)
               return redirect('home')
    else:
        form=AuthenticationForm()
    return render(request, 'login.html', {'form':form})

def logout_view(request):
    logout(request)
    return redirect('home')

mydiary/views.py
from tokenize import maybe
from django.shortcuts import render,redirect, get_object_or_404
from django.utils import timezone
from .models import Content,Comment, Tag, Image
from .forms import ContentForm, CommentForm, TagForm
# Create your views here.

def home(request):
    posts=Content.objects.all()
    return render(request, 'mydiary/home.html', {'posts_list':posts})

def aboutus(request):
    return render(request, 'mydiary/aboutus.html')

def forlion(request):
    return render(request, 'mydiary/forlion.html')

def recruit(request):
    return render(request,'mydiary/recruit.html')
def QA(request):
    return render(request,'mydiary/QA.html')
def new(request):
    if request.method=='POST':
        form= ContentForm(request.POST, request.FILES)
        if form.is_valid():
            post=form.save(commit=False)
            post.author=request.user
            post.published_date=timezone.now()
            post.save()
            for img in request.FILES.getlist('imgs'):
                image=Image()
                image.post=post
                image.file=img
                image.save()
            return redirect('home')
    else:
        form=ContentForm()
    return render(request,'mydiary/new.html',{'form':form})

def detail(request,index):
    post=get_object_or_404(Content, pk=index)
    comment_list=Comment.objects.filter(post=post)
    if request.method=="POST":
        comment_form =CommentForm(request.POST)
        if comment_form.is_valid():
            comment=comment_form.save(commit=False)
            comment.published_date=timezone.now()
            comment.post=post
            comment.save()
            return redirect('detail',index=index)
    else:
        comment_form=CommentForm()
        tag_form=TagForm()
    return render(request, 'mydiary/detail.html', {'post':post, 'comment_list':comment_list, 'comment_form':comment_form, 'tag_form':tag_form})

def edit(request,index):
    post=get_object_or_404(Content,pk=index)
    if request.method=="POST":
        form= ContentForm(request.POST, request.FILES,instance=post)
        if form.is_valid():
            post=form.save(commit=False)
            post.author=request.user
            post.published_date=timezone.now()
            post.save()
            return redirect('detail',index=post.pk)
    else:
        form=ContentForm(instance=post)
    return render(request,'mydiary/edit.html',{'form':form})

def delete(request,pk):
    post=get_object_or_404(Content, pk=pk)
    post.delete()
    return redirect('home')

def delete_comment(request, index, comment_pk):
    comment=get_object_or_404(Comment, pk=comment_pk)
    comment.delete()
    return redirect('detail', index=index)

def tag_add(request,pk):
    post=get_object_or_404(Content,pk=pk)
    tag_form=TagForm(request.POST)
    if tag_form.is_valid():
        tag=tag_form.save(commit=False)
        tag,created= Tag.objects.get_or_create(name=tag.name)
        post.tags.add(tag)
        return redirect('detail',index=pk)

def tag_home(request):
    tags=Tag.objects.all()
    return render(request,'tag.html', {'tags':tags})

def tag_detail(request,pk):
    tag=get_object_or_404(Tag,pk=pk)
    tag_posts= tag.content_set.all()
    return render(request, 'tag_detail.html', {'tag':tag, 'tag_posts':tag_posts})

def tag_delete(request,pk,tag_pk):
    post=get_object_or_404(Content,pk=pk)
    tag=get_object_or_404(Tag,pk=tag_pk)
    post.tags.remove(tag)
    if tag.content_set.count()==0:
        tag.delete()
    return redirect('detail',index=pk)

accounts/templates/login.html
<h1>Login</h1>

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">submit</button>
</form>

accounts/templates/signup.html
<h1>Sign Up</h1>

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">submit</button>
</form>

mydiary/templates/mydiary/QA.html
{% extends 'mydiary/base.html' %}
{% block content %}
{% load static %}


    <head>
        <meta charset="utf-8">
        <title>질의응답</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="stylesheet" media = "screen and (min-device-width: 375px) and (max-device-width: 812px)" href="{% static 'css/QA.css'%}">
        <link rel="stylesheet" href="{% static 'css/QA.css'%}">
    </head>

    <body>
        <div class="QA-header">
            <img class = "image1" src="{%static 'img/hack your life.png'%}" alt="hack your life 이미지">
            <div class="header-text">
                <span class="white-header">멋쟁이 사자처럼 </span>
                <span class="orange-header">홍익대 10기</span>
                <div class="orange-header">운영진 소개 & QA </div>
            </div>
        </div>

        <div class = "QA-word">
            <span class="orange-introduce">홍익대 멋사 10기</span><span class="white-introduce">를 이끌어 갈 운영진을 소개합니다! 🧡</span>
        </div>

        <div class="QA-introduce">
            <div class="QA-introduce-people">
                <div id="people-box-moblie1">
                    <div class="people-box">
                        <div class="people-image-box">
                            <img class = "people-image-real" src="{%static 'img/people/doyeon.png'%}" alt="doyeon" style="width:100%; height:100%; object-fit:cover;">
                        </div>
                        <p class="white-name">김도연</p>
                        <p class="white-describe">해보지 않고는 당신이 무엇을 해낼 수 있는지 알 수 없다. 🦁 </p>
                    </div>
                    <div class="people-box">
                        <div class="people-image-box" >
                            <img class = "people-image-real" src="{%static 'img/people/jihu.png'%}" alt="jihu" style="width:100%; height:100%; object-fit:cover;">
                        </div>
                            <p class="white-name">김지후</p>
                            <p class="white-describe">멋사 10기가 되어서 협업 경험도 쌓고, 좋은 추억도 만들어요. 고민하지 말고 지원해주세요~! </p>
                    </div>
                    <div class="people-box">
                        <div class="people-image-box">
                            <img class = "people-image-real" src="{%static 'img/people/eugene.png'%}" alt="eugene" style="width:100%; height:100%; object-fit:cover;">
                        </div>
                        <div class="caption-box" style="margin:10px;">
                            <span class="orange-name">대표</span><span class="white-name">김유진</span>
                        </div>
                        <p class="white-describe">개발 경험을 쌓고 싶은 학생들 환영해요. 초보자도 환영해요! 함께 멋있는 서비스 만들어요. </p>
                    </div>
                    <div class="people-box">
                        <div class="people-image-box">
                            <img class = "people-image-real" src="{%static 'img/people/sunhyeong.png'%}" alt="sunhyeong" style="width:100%; height:100%; object-fit:cover;">
                        </div>
                        <p class="white-name">박선형</p>
                        <p class="white-describe">🦁되면 하는 것이 아니라 하면 됩니다! 여러분들의 생각을 실현시켜보세요!🦁 </p>
                    </div>
                    <div class="people-box">
                        <div class="people-image-box"id="people-box-moblie2">
                            <img class = "people-image-real" src="{%static 'img/people/eun.png'%}" alt="eun" style="width:100%; height:100%; object-fit:cover;">
                        </div>
                        <p class="white-name">이은</p>
                        <p class="white-describe">망설이기 보다는 불완전하게 시작하는 것이 한걸음 앞서 가는 것 입니다. 고민은 멋쟁이가 되기를 늦출 뿐!😎 </p>
                    </div>
                </div>
            </div>
        </div>

        <section class="QA">
            <div class="question-box">
                <div class="caption-Q">Q.</div>
                <div class="question">개발,디자인 Track 과 개발 Track에 대해 자세히 말해주세요.</div>
            </div>
            <div class="answer-box">
                <div class="answer-white"> 모든 Track에게는 개발의 기초 소양인 HTML/CSS과 Python에 대한 교육이 진행됩니다.<br> 이후 기획/디자인 파트는 멋사 Head of Product 이지훈님과 Head of Design인 김지홍님의 특강이 제공됩니다.
                    <br>개발 Track 중 프론트엔드 파트를 선택한 경우에는 자바스크립트 + 알파 교육, 백엔드 파트를 선택한 경우 장고 교육이 진행됩니다.</div>
            </div>

            <div class="question-box">
                <div class="caption-Q">Q.</div>
                <div class="question">학생 교육 일정을 자세히 알려주세요.</div>
            </div>
            <div class="answer-box">
                <div class="answer-white">3월 28일부터 약 1~2주간 HTML/CSS 교육을 진행합니다.<br> 중간고사 기간 이후 5월 2일부터 2주간 python 기초, 심화 교육을 진행합니다. 
                    <br> 5월 16일부터 6월 말까지 기획, 디자인 트랙은 특강 교육이 진행되고 개발트랙(프론트엔드/백엔드-Django)에 대한 교육이 진행됩니다. 
                    <br> 이후 7월 첫주부터 아이디어톤 준비, 이후 아이디어톤과 해커톤 활동이 이어집니다.</div>
            </div>

            <div class="question-box">
                <div class="caption-Q">Q.</div>
                <div class="question">개발 경험이 없고, 프로그래밍 초보인데 괜찮을까요?</div>
            </div>
            <div class="answer-box">
                <div class="answer-white">괜찮습니다!! 멋쟁이 사자처럼은 코딩 초보자도 자신의 서비스를 만들고 멋쟁이 사자처럼을 수료하는 것을 목적으로 합니다.<br> 
                    이를 위해 꼼꼼히 지도하고 위에 소개된 운영진이 많은 도움을 줄 것입니다 :) </div>
            </div>

            <div class="question-box">
                <div class="caption-Q">Q.</div>
                <div class="question">매주 세션은 언제 어떻게 진행되나요?</div>
            </div>
            <div class="answer-box">
                <div class="answer-white">매주 세션은 주 1회 저녁시간에 진행됩니다. <br> 기획/디자인 파트 1명, 개발 Track 2~3명, 운영진 1명으로 팀 빌딩을 하여 매주 2h 정도 소요되는 세션을 진행합니다.
                 Code Lion의 강의 내용과 제공되는 교육 자료를 바탕으로 실습을 진행하고, 실습에 대한 피드백, 멘토링 활동이 이루어질 예정입니다. 코로나 19의 상황이 좋아지는 대로 오프라인으로 진행하는 것을 추진할 것입니다. </div>
            </div>

            <div class="question-box">
                <div class="caption-Q">Q.</div>
                <div class="question">지원서를 어떻게 작성하나요?</div>
            </div>
            <div class="answer-box">
                <div class="answer-white">지원서는 홍대 멋사 소개 홈페이지 메인 화면에 '지원서 작성하기'버튼을 통해 접속한 구글 폼 링크에서 작성하시면 됩니다. 인스타그램에도 모집 링크를 걸어놓았으니, 인스타그램도 확인해주세요! </div>
            </div>

            <div class="question-box">
                <div class="caption-Q">Q.</div>
                <div class="question">합격 결과는 어디서 확인하나요?</div>
            </div>
            <div class="answer-box">
                <div class="answer-white">서류 합격은 3월 15일에 발표합니다. 합격자에게는 지원서에 작성하신 연락처로 개별적으로 연락이 갈 예정이므로 3월 15일에 문자를 꼭 확인해 주세요! <br>
                개별 연락을 통해 면접 일정을 안내드립니다. </div>
            </div>

            <div class="question-box">
                <div class="caption-Q">Q.</div>
                <div class="question">더 질문이 있는데..어떻게 하죠?</div>
            </div>
            <div class="answer-box">
                <div class="answer-white">추가적인 질문은 홍익대학교 인스타그램 @likelion.hongik의 DM으로 연락 주시기 바랍니다. 친절히 답변 드리겠습니다!  </div>
            </div>
        </section>

        <footer>홍익대학교 멋쟁이 사자처럼 10기 대표 김유진<br>TEL: 010-9937-4176<br>홍익대학교 멋쟁이 사자처럼 10기 운영진<br>김도연 김지후 박선형 이은</footer>
    </body>

{% endblock %}

mydiary/templates/mydiary/aboutus.html
{% extends 'mydiary/base.html' %}
{% block content %}
{% load static %}
<!doctype html>
<html lang="ko">
    <head> 
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;500;600;700&display=swap" rel="stylesheet">
    </head>
    <body class="background">
            <section class="mainbox">
                <div class="header">
                    <div style="float:left; margin-top: 10px;"><img class="img" src= '{%static "Likelion_project/likelion_logo_white.png"%}' width = "200" height="120"></div>
                    <div class='txt_box' style="float:left;">
                        <h1 class="text title">HACK YOUR LIFE!</h1>
                        <h3 class="text subtitle">멋쟁이 사자처럼 소개</h3>
                    </div>
                </div>
            </section>
            <section class="contents">
                <p class="Q-title">🦁 멋쟁이 사자처럼은 어떤 동아리인가요?</p>
                <p class="contents-txt"> 멋쟁이 사자처럼은 “내 아이디어를 내 손으로 실현한다” 라는 가치 아래 전국 대학을 포함한 세계 130여 대학에서 선발된 8,400여명의 학생들이 활동하였습니다.
                    교육 프로그램을 통해 1,000여개의 서비스가 제작되었습니다. (2021년 1월 기준)</p>
                <p class="contents-txt"> 멋쟁이사자처럼 대학은 온라인 기반의 강의와 오프라인 활동이 함께 이루어지는 코딩 교육 동아리입니다.
                    코딩을 배우고, 자신만의 서비스를 만들어보고 싶은
                    대학생을 위한 IT 연합 동아리입니다. 컴퓨터를 모르는 학생들이 프로그래밍 교육을 통해 원하는 IT서비스를 직접 런칭합니다.</p> 
                <p class="contents-txt"> 현재 국내에서 가장 많은 학생들이 활동하고 있는 프로그래밍 교육 프로그램이며, 현재는 Python & Django 기반으로 교육을 진행하고 있습니다.</p>   
                
                <p class="Q-title">🦁 멋쟁이 사자처럼에서 어떤 활동을 하나요?</p>
                <img style="width: 900px; display: block; margin: 0 auto;"src='{%static "Likelion_project/hackton_img.jpeg"%}'>
                <p class="contents-txt">▶ <mark class="orange">교육</mark>: 멋쟁이 사자처럼의 교육 서비스인 ‘Code lion’을 통해, 멋사에서 제공하는 강의를 듣고 웹 기초에 대해 공부합니다. html, css, python, django, github 에 대해 교육합니다. 자신의 웹 서비스를 만들 수 있는 역량을 쌓을 수 있습니다.</p>
                <p class="contents-txt">▶ <mark class="orange">프로젝트 및 서비스 빌딩</mark>: 동아리원들과 팀 빌딩을 하여 서비스를 직접 기획하고, 프로젝트를 진행하여 협업 능력을 키우며 나의 서비스를 내 손으로 직접 만드는 소중한 경험을 할 수 있습니다.</p>
                <p class="contents-txt">▶ <mark class="orange">아이디어톤, 해커톤</mark>: 교육 시 배운 내용을 바탕으로 하여 동아리원들과 팀을 이루어 멋사에서 진행하는 아이디어톤과 해커톤에 참여합니다. 위 사진은 오프라인 해커톤의 모습입니다. 전국의 멋쟁이 사자처럼 회원들과 경쟁하는 대형 해커톤에 참여할 수 있습니다.</p>
                
                <p class="Q-title"> 🦁 멋쟁이 사자처럼 선배님들의 발자취 </p>
                <div class="top">
                    <img src='{%static "Likelion_project/tailing_1.png"%}'width='400px' height="300px" style="margin-top: 15px; margin-left:30px">
                    <img src='{%static "Likelion_project/gudak_.png"%}'width='450px' height="400px"style="margin-left:30px">
                    <img src='{%static "img/베프로.png"%}' width='450px' height="300px" style="margin-left:20px;">
                    <img src='{%static "img/jasosul_.png"%}'width='350px' height="300px" >
                </div>
    
                <div class="bottom">
                    <img src='{%static "Likelion_project/slid_logo_with_text.png"%}'width=100px height="100px" style="margin-right:100px;">
                    <img src='{%static "Likelion_project/drymuri_logo.png"%}'width=90px height="100px"style="margin-right:150px;">
                    <img src='{%static "Likelion_project/chunmyung_logo.png"%}'width=100 height="100px" style="margin-right:100px;">
                    <img src='{%static "Likelion_project/quotabook2_logo.png"%}'width=100 height="80px">
                </div>
                <p class="Q-title" style="margin-top: 50px;"> 🎆 홍익대학교 멋쟁이 사자처럼 7기 제작, 홍대 축제 소개 서비스 🎆</p>
                <img src='{%static "Likelion_project/홍익 페스티벌_7기.jpg"%}'width="900" height="500px"style="padding: 50px;">
                <button class="btn" type="button" onclick="location.href= 'https://hongik-festival.herokuapp.com/'">접속하기</button>
                
    
                <p class="Q-title" style="margin-top: 30px;">🦁 멋쟁이 사자처럼 9기는 무슨 활동을 했나요?</p>
                <img src='{%static "Likelion_project/동방예의지국_9기 아이디어톤.JPG"%}'width="900px" height="500px"style="padding: 50px;">
                <img src='{%static "Likelion_project/선배님.png"%}'width="900px" height="500px"style="padding: 50px;">
                <img src='{%static "Likelion_project/어흥올림픽_9기 연합해커톤.png"%}'width="900px" height="500px"style="padding: 50px;">           
            </section> 
    </body>
    <footer>홍익대학교 멋쟁이 사자처럼 10기 대표 김유진<br>TEL: 010-9937-4176<br>홍익대학교 멋쟁이 사자처럼 10기 운영진<br>김도연 김지후 박선형 이은</footer>
    </footer>  
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@200&family=Montserrat:ital,wght@0,100;0,200;0,300;1,100&display=swap');

        *{
            font-family:'Montserrat';
        }

        .wrap{
            margin: 0 auto;
            display: block;
        }
        .background{
            background-color: black;
        }
        .header{
            width: 980px;
            display:block;
            margin: 0 auto;
            margin-top: 50px;
            padding-left: 50px;
        }
        .text{
            color: white;
            display: inline-blodk;
        }
        .text.title {margin: auto; margin-bottom: auto; font-weight: bold; font-size: 75px;}
        .text.subtitle{font-size: 40px;}

        .contents{
            margin:0 auto;
            width: 980px;
            display: block;
            /* margin: 0 auto; */
            border-top: solid 1px gray;
            margin-top: 250px;
            padding-left: 20px;
            padding-right: 20px;;
        }
        .Q-title{
            padding-top: 50px;
            color: white;
            font-size: 30px;
            font-weight: bold;
        }
        .contents-txt{
            padding-top: 20px;
            color: white;
            font-size: 20px;
        }
        .img-txt{
            color:white;
            font-size:25px;
            text-align: center;
        }
        .img-txt.sub{font-size:20px;}
        mark.orange{
            color: orange;
            background:none;
            font-weight: bold;
        }
        mark.red{
            color:red;
            background: none;
        }
        mark.blue{
            color:blue;
            background: none;
        }
        .box{
            margin: 0 auto;
        }
        .box.left{float:left; width:600px; margin-top:40px;}
        .box.right{float:right; width: 600px; margin-top:40px;}

        .btn{
            width:250px;
            height: 60px;
            background-color: orange;
            color: white;
            font-size: 25px;
            margin-top: 30px;
            margin-bottom: 30px;
            border-color: orange;
            border-radius: 12px;
            margin:auto;
            display: block;
        }
        footer{
            height: 38px;
            position : relative;
            /* transform: translateY(-100%); */
            text-align: left;
            color: gray;
        }

        nav{
            position: fixed;
            top:0;
            /* left: 0;
            right: 0; */
            width:100%;
        }

        .bottom{
            margin: 0 auto;
            display: block;
            padding-left: 50px;
        }

    </style>   
</html>
{% endblock %}

mydiary/templates/mydiary/detail.html
{% extends 'mydiary/base.html' %}
{% block content %}
{% load static %}
<h1>DIARY DETAIL</h1>
<div>
    {% if post.pub_date %}
    <div>
        {{post.pub_date}}
    </div>
    {% endif %}
    <h1>{{post.title}}</h1>
    <p>{{post.body|linebreaks}}</p>
    {% for image in post.image_set.all %}
        <img src="{{image.file.url}}" width="450"><br>
        {% endfor %}
    {% if post.image %}
        <img src="{{post.image.url}}" height=400><br>
        이미지 다운: <a href="{{post.image.url}}" download>{{post.image.name}}</a>
    {% endif %}
</div>


<form action="{% url 'tag_add' pk=post.pk %}" method="POST">
    {% csrf_token %}
    {{tag_form.name}}
    <input type="submit" value="해시태그 추가">
</form>

<p>
    {% for t in post.tags.all %}
    <b>#{{t.name}}</b>
    <a href="{% url 'tag_delete' pk=post.pk tag_pk=t.pk %}">X</a>
    {% endfor %}
</p>

<form method="POST">
    {% csrf_token %}
    <input type="text" name="text">
    <button type="submit">댓글 달기</button>
</form>

{% for comment in comment_list %}
<h5>{{comment.created_date}}</h5>
<p>{{comment.text|linebreaks}}</p>
<a href="{% url 'delete_comment' index=post.pk comment_pk=comment.pk %}">댓글 삭제</a>
{% endfor %}


<a href="{%url 'edit' index=post.pk %}">edit</a><br>
<a href="{% url 'delete' pk=post.pk %}">delete</a>
{% endblock %}

mydiary/templates/mydiary/edit.html
{% extends 'mydiary/base.html' %}
{% block content %}
{% load static %}
<h1>일기 수정하기</h1>
    <form method="POST" enctype='multipart/form-data'>{% csrf_token%}
        {{form.as_p}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

mydiary/templates/mydiary/new.html
{% extends 'mydiary/base.html' %}
{% block content %}
{% load static %}
<h1>새 일기를 쓰는 페이지 입니다.</h1>

<form method="POST" enctype='multipart/form-data'>{% csrf_token%}
    {{form.as_p}}
    <input type="file" name="imgs" multiple>
    <button type="submit">저장하기</button>

</form>
{% endblock %}

mydiary/templates/mydiary/tag.html
<h1>HashTag</h1>

{% for tag in tags %}
<a href="{% url 'tag_detail' pk=tag.pk %}">#{{tag.name}}</a>
{{tag.contetn_set.count}}
<br><br>
{% endfor %}

mydiary/templates/mydiary/tag_detail.html
<h1>#{{tag}}</h1>
<h3>해시태그를 포함한 게시글 {{tag_posts.count}}개</h3>
<div class="posts">
    {% for post in tag_posts %}
    <a href="{% url 'detail' pk=post.pk %}">{{post.title}}</a>
    <br><br>
    {% endfor %}
</div>